# Introduction to NumPy

NumPy (Numerical Python) is a Python library for scientific computing, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), the performance is very good.

[Official Documentation](https://numpy.org/)

It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.

**How are NumPy arrays different from Python lists?**
 - Python lists are very general. They can contain any kind of object. They are dynamically typed.
 - They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
 - Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
 - Numpy arrays are memory efficient.
 - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

## Creating N-dimensional NumPy arrays

### Loading Libraries

First, let's import the necessary libraries:

In [ ]:
import numpy as np

# check version
np.__version__

'1.26.4'

There are a number of ways to initialize new numpy arrays, for example from

 - a Python list or tuples
 - using functions that are dedicated to generating numpy arrays, such as numpy.arange, numpy.linspace, etc.
 - reading data from files

### From lists

To create new vector and matrix arrays using Python lists we can use the numpy.array() function.

In [ ]:
# a vector: the argument to the array function is a Python list
# more generally, 1D array
lst = [1,2,3,4.0]
v = np.array(lst, dtype=np.int32)

v

array([1, 2, 3, 4], dtype=int32)

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# a matrix: the argument to the array function is a nested Python list (can also be a tuple of tuples)
# more generally, a 2D array
list_of_lists = [[1, 2], [3, 4]]
M = np.array(list_of_lists)

M

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[1, 2],
       [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
# a row vector

row_vec = v[np.newaxis, :]  # v[None, :]
row_vec

array([[1, 2, 3, 4]], dtype=int32)

In [ ]:
np.array([[1, 2, 3, 4]], dtype=np.int32)

array([[1, 2, 3, 4]], dtype=int32)

In [ ]:
# a column vector
col_vec = v[:, np.newaxis]  # v[:, None]
col_vec

array([[1],
       [2],
       [3],
       [4]], dtype=int32)

In [ ]:
np.array([[1],
       [2],
       [3],
       [4]], dtype=np.int32)

array([[1],
       [2],
       [3],
       [4]], dtype=int32)

### Construction using intrinsic array generating functions

NumPy provides many functions for generating arrays. Some of them are:

 - numpy.arange()
 - numpy.linspace()
 - numpy.logspace()
 - numpy.random.

In [ ]:
# when using linspace, both end points ARE included
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.logspace(0, 5, 10, base=np.e)

array([  1.        ,   1.742909  ,   3.03773178,   5.29449005,
         9.22781435,  16.08324067,  28.03162489,  48.85657127,
        85.15255772, 148.4131591 ])

In [ ]:
# a 3D array
# a random array where the values come from a standard Normal distribution
gaussian = np.random.randn(2 * 3 * 4)

# reshape the array to desired shape.
# only the number of dimensions can be altered
# the number of elements CANNOT be changed during a reshape operation

gaussian = gaussian.reshape(2, 3, 4)
gaussian

array([[[ 0.93996067,  1.24303005, -0.07681034,  1.53630215],
        [-0.39628592,  0.65743747,  0.55091715, -2.13718422],
        [-1.15091693, -0.17115183, -0.42711447,  0.44720991]],

       [[-0.60787391, -0.85017823,  0.97683079, -0.26011945],
        [-0.76291803, -0.25414269, -0.32138349, -0.77476096],
        [-0.84726026,  2.37619033,  2.03851332, -0.77507687]]])

In [ ]:
# an array full of zero values
# one can also specify a desired datatype

zero_arr = np.zeros((3, 4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# an array full of ones
# one can also specify datatype

ones_arr = np.ones((3, 4), dtype=np.float32)
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
# a 3x3 identity (matrix) array

iden = np.identity(3, dtype=np.float128)  # np.eye(4, dtype=np.float128)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float128)

In [ ]:
# a diagonal array

diag = np.diag([1, 2, 3, 4.0])
diag

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

## NumPy Array Attributes

Attributes of arrays include:
- **Determining the size, shape, memory consumption, and data types of arrays**
- **Indexing of arrays**: Getting and setting the value of individual array elements
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array
- **Reshaping of arrays**: Changing the shape of a given array
- **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many

Each array has attributes such as:

- `ndim`: The number of dimensions
- `shape`: The size of each dimension
- `size`: The total number of elements in the array

In [ ]:
# a 3D random array where the values come from a standard Normal distribution
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# get number of dimensions of the array
gaussian.ndim
print("total dimensions of the array is: ", gaussian.ndim)

# get the shape of the array
gaussian.shape
print("the shape of the array is: ", gaussian.shape)

# get the total number of elements in the array
gaussian.size
print("total number of items is: ", gaussian.size)

# get memory consumed by each item in the array
gaussian.itemsize
print("memory consumed by each item is: ", gaussian.itemsize)

# get memory consumed by the array
gaussian.nbytes
print("total memory consumed by the whole array is: ", gaussian.nbytes)

total dimensions of the array is:  3
the shape of the array is:  (2, 3, 4)
total number of items is:  24
memory consumed by each item is:  8
total memory consumed by the whole array is:  192


## Array Indexing

We can index elements in an array using square brackets and indices. For 1D arrays, indexing works the same as with Python list.

In [ ]:
# 1D array of random integers
# get 10 integers from 0 to 23

num_samples = 10
integers = np.random.randint(23, size=num_samples)
integers

array([18, 12, 15, 18,  5,  5, 11, 16, 12, 14])

In [ ]:
# indexing 1D array needs only one index
# get 3rd element (remember: NumPy unlike MATLAB is 0 based indexing)
integers[2]

15

In [ ]:
twoD_arr = np.arange(1, 46).reshape(3, -1)
twoD_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
# indexing 2D array needs only two indices.
# then it returns a scalar value

# value at last row and last column
twoD_arr[-1, -1]

45

In [ ]:
# however, if we use only one (valid) index then it returns a 1D array

# get all elments in the last row
twoD_arr[-1]  # or twoD_arr[-1, ] or twoD_arr[-1, :]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [ ]:
# remember `gaussian` is a 3D array.
gaussian

array([[[-0.63720896, -0.58187428,  2.38685407,  0.53663879],
        [ 0.95831579, -0.0446415 , -0.68606276, -1.12292585],
        [ 0.1744492 ,  0.96085526, -0.7287163 ,  1.38716755]],

       [[ 0.51950902, -2.58781142, -1.42527904,  1.71485703],
        [-0.79579522, -1.33554042, -0.39889601, -2.34066178],
        [ 0.78325111, -0.17855909,  0.22240456, -1.52571642]]])

In [ ]:
# So, a 2D array is returned when using one index

# return last slice
gaussian[-1]

array([[ 0.51950902, -2.58781142, -1.42527904,  1.71485703],
       [-0.79579522, -1.33554042, -0.39889601, -2.34066178],
       [ 0.78325111, -0.17855909,  0.22240456, -1.52571642]])

In [ ]:
# a 1D array is returned when using a pair of indices

# return first row from last slice
gaussian[-1, 0]

array([ 0.51950902, -2.58781142, -1.42527904,  1.71485703])

In [ ]:
# return last row from last slice
gaussian[-1, -1]

array([ 0.78325111, -0.17855909,  0.22240456, -1.52571642])

In [ ]:
# return last element of row of last slice
idx = (-1, -1, -1)
gaussian[idx]

-1.52571641608341

We can also assign new values to elements in an array using indexing:

In [ ]:
# updating the array by assigning values
# truncation will happen if there's a datatype mismatch
#print(integers)
integers[2] = 99.21
integers

array([18, 12, 99, 18,  5,  5, 11, 16, 12, 14])

## Index slicing

Index slicing is the technical name for the syntax M[lower:upper:step] to extract part of an array.
Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
integers

array([18, 12, 99, 18,  5,  5, 11, 16, 12, 14])

In [ ]:
# slice a portion of the array
# similar to Python iterator slicing
# x[start:stop:step]

# get last 5 elements
integers[-5:]

# if `stop` is omitted then it'll be sliced till the end of the array
# by default, step is 1

array([ 5, 11, 16, 12, 14])

In [ ]:
# get alternative elements (every other element) from the array
# equivalently step = 2

integers[::2]

array([18, 99,  5, 11, 12])

In [ ]:
# reversing the array
integers[::-1]

array([14, 12, 16, 11,  5,  5, 18, 99, 12, 18])

In [ ]:
# forward traversal of array
integers[3::]

array([18,  5,  5, 11, 16, 12, 14])

In [ ]:
# reverse travesal of array (starting from 4th element)
integers[3::-1]

array([18, 99, 12, 18])

Array slices are mutable: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
integers

array([18, 12, 99, 18,  5,  5, 11, 16, 12, 14])

In [ ]:
# assign new values to the last two elements
integers[-2:] = [-23, -46]

integers

array([ 18,  12,  99,  18,   5,   5,  11,  16, -23, -46])

## nD arrays

In [ ]:
# a 2D array
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# slice first 2 rows and 3 columns
twenty[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [ ]:
# slice and get only the corner elements
# three "jumps" along dimension 0
# four "jumps" along dimension 1
twenty[::3, ::4]

array([[ 0,  4],
       [15, 19]])

In [ ]:
# reversing the order of elements along columns (i.e. along dimension 0)
twenty[::-1, ...]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
# reversing the order of elements along rows (i.e. along dimension 1)
twenty[..., ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [ ]:
# reversing the rows and columns (i.e. along both dimensions)
twenty[::-1, ::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [ ]:
# or more intuitively
np.flip(twenty, axis=(0, 1))

# or equivalently
np.flipud(np.fliplr(twenty))
np.fliplr(np.flipud(twenty))

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Fancy indexing

Fancy indexing is the name for when an array or a list is used in-place of an index:

In [ ]:
# a 2D array
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# get 2nd, 3rd, and 4th rows
row_indices = [1, 2, 3]
twenty[row_indices]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
twenty[row_indices, col_indices]

array([ 6, 12, 19])

We can also use index masks: If the index mask is a NumPy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element

In [ ]:
# 1D array
integers

array([ 18,  12,  99,  18,   5,   5,  11,  16, -23, -46])

In [ ]:
# mask has to be of the same shape as the array to be indexed; else IndexError would be thrown
# mask for indexing alternate elements in the array
row_mask = np.array([True, False, True, False, True, False, True, False, True, False])

integers[row_mask]

array([ 18,  99,   5,  11, -23])

In [ ]:
# alternatively
row_mask = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=bool)

integers[row_mask]

array([ 18,  99,   5,  11, -23])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
mask = (range_arr > 5) * (range_arr < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [ ]:
range_arr[mask]

array([5.5, 6. , 6.5, 7. ])

In [ ]:
# or equivalently

mask = (5 < range_arr) & (range_arr < 7.5)
range_arr[mask]

array([5.5, 6. , 6.5, 7. ])

## Linear operations

Vectorizing the code is key to writing efficient numerical calculation with Python/NumPy. This means that, as much as possible, a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
vec = np.arange(0, 5)

vec

array([0, 1, 2, 3, 4])

In [ ]:
# note that original `vec` still remains unaffected since we haven't assigned the new array to it.
vec * 2

array([0, 2, 4, 6, 8])

In [ ]:
vec + 2

array([2, 3, 4, 5, 6])

### Element-wise array-array operations

When we add, subtract, multiply, and divide arrays with each other, the default behaviour is element-wise operations:

In [ ]:
arr = np.arange(4 * 5).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.matmul(arr, (arr.T))


array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [ ]:
print(vec.shape, arr.shape)

# shape has to match
vec * arr

(5,) (4, 5)


array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

In [ ]:
# else no broadcasting will happen and an error is thrown
#print(vec[:, None].shape)

vec[:, None] * arr

ValueError: operands could not be broadcast together with shapes (5,1) (4,5) 

In [ ]:
# however, this would work
vec[:4, None] * arr

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [45, 48, 51, 54, 57]])

## Matrix operations

What about the glorified matrix mutiplication? There are two ways. We can either use the dot function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments. Or you can use the @ operator in Python 3

In [ ]:
# matrix-matrix product
print(arr.T.shape, arr.shape)
np.dot(arr.T, arr)

(5, 4) (4, 5)


array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [ ]:
# matrix-vector product
print("shapes: ", arr.shape, vec.shape)
np.dot(arr, vec)   # but not this: np.dot(vec, arr)

shapes:  (4, 5) (5,)


array([ 30,  80, 130, 180])

In [ ]:
col_vec = vec[:, None]
print("shapes: ", (col_vec).T.shape, (col_vec).shape)

# inner product
(col_vec.T) @ (col_vec)

shapes:  (1, 5) (5, 1)


array([[30]])

### Stacking and repeating arrays

Using function repeat, tile, vstack, hstack, and concatenate we can create larger vectors and matrices from smaller ones:

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
# tile the matrix 3 times
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [ ]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [ ]:
# concatenate a and b along axis 0
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# concatenate a and b along axis 1
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### hstack and vstack

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Copy and "deep copy"

For performance reasons, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference).

In [ ]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [ ]:
# now array B is referring to the same array data as A
B = A
B

array([[1, 2],
       [3, 4]])

In [ ]:
# changing B affects A
B[0,0] = 10

A

array([[10,  2],
       [ 3,  4]])

If we want to avoid such a behavior, so that when we get a new completely independent object B copied from A, then we need to do a so-called "deep copy" using the function copy:

In [ ]:
B = np.copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0,0] = -5

A

array([[10,  2],
       [ 3,  4]])

## Vectorizing functions

As mentioned several times by now, to get good performance we should always try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [ ]:
def Theta(x):
    """
    scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
v1 = np.array([-3,-2,-1,0,1,2,3])

Theta(v1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
"""That didn't work because we didn't write the function Theta so that it can handle a vector input...

To get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:"""

"That didn't work because we didn't write the function Theta so that it can handle a vector input...\n\nTo get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:"

In [ ]:
Theta_vec = np.vectorize(Theta)

In [ ]:
Theta_vec(v1)

array([0, 0, 0, 1, 1, 1, 1])

In [ ]:
"we can also implement the function to accept a vector input f2rom the beginning (requires more effort but might give better performance):

SyntaxError: invalid syntax (<ipython-input-89-1f275f8b80de>, line 1)

In [ ]:
def Theta(x):
    """
    Vector-aware implementation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [ ]:
Theta(v1)

In [ ]:
# it even works with scalar input
Theta(-1.2), Theta(2.6)

## Exercices

### Exercise 1: Creating and Manipulating NumPy Arrays

- Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.

- Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

- Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.

In [ ]:
L=[5, 10, 15, 20, 25]
arr=np.array(L,dtype=np.float64)
arr

array([ 5., 10., 15., 20., 25.])

In [ ]:
L_2D=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2D=np.array(L_2D)
print(f"the 2D_array:\n {arr_2D} \n The form:{arr_2D.shape}\n The size : {arr_2D.size}")

the 2D_array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 The form:(3, 3)
 The size : 9


In [ ]:
arr_3D=np.random.random((2,3,4)) ; arr_3D

array([[[0.28917099, 0.09239308, 0.81083298, 0.82872246],
        [0.45450298, 0.98065166, 0.1615572 , 0.68392235],
        [0.46754061, 0.52132168, 0.84242974, 0.26843378]],

       [[0.30716874, 0.30111466, 0.02383552, 0.3596453 ],
        [0.42076572, 0.14627423, 0.84320203, 0.80835658],
        [0.99371223, 0.74235076, 0.31451843, 0.74238645]]])

### Exercise 3: Advanced Array Manipulations

- Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.

- Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

- Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.

In [ ]:
np.array(range(10)[::-1])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr_2D_11=np.array(range(12)).reshape(3,4);arr_2D_11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
subarray =arr_2D_11[:2, -2:] ;subarray

array([[2, 3],
       [6, 7]])

### Exercise 4: Array Initialization and Attributes

- Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.

- Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.

- Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.

In [ ]:
id_3=np.eye(3);id_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
print(id_3.ndim)
print(id_3.size)
print(id_3.shape)
print(id_3.itemsize)
print(id_3.nbytes)

2
9
(3, 3)
8
72


In [ ]:
array_3D = np.random.randn(2, 3, 4);
print(array_3D)
print(array_3D.sum())

[[[ 0.03895117 -0.57918125  0.11451128  0.4425767 ]
  [ 1.08984462  0.87921088  1.72230158 -0.00506956]
  [ 1.28089824 -0.44509172  0.48936408  2.47706006]]

 [[ 0.13156701  0.53563453  0.69221413 -0.06698679]
  [ 0.01929105 -0.33286071 -1.30623052  2.91557849]
  [-1.25098046 -1.11236535 -0.53973983 -0.32687508]]]
6.863622539524543


### Exercise 5: Fancy Indexing and Masking

- Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

- Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.

- Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [ ]:
A=np.array(np.random.randint(0,50,20));A


array([24, 27, 23, 32, 16,  9,  6, 38, 28,  7, 25, 45, 30, 14, 25, 46, 39,
        0, 24, 45])

In [ ]:
indices=[2,5,7,10,15];A[indices]

array([23,  9, 38, 25, 46])

In [ ]:
array_2D = np.random.randint(0, 31, size=(4, 5))
mask = array_2D > 15
selected_elements = array_2D[mask] ;selected_elements

array([22, 20, 24, 23, 25, 26, 24, 22, 28, 21])

### Exercise 7: Combining and Splitting Arrays

- Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.

- Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.

- Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.

In [ ]:
array_1 = np.random.randint(0, 11, size=5)
array_2 = np.random.randint(0, 11, size=5)
concatenated_array = np.concatenate((array_1, array_2)) ;concatenated_array

array([ 7,  9,  2, 10,  5,  9,  5,  3,  9,  7])

In [ ]:
array_3=np.random.randint(0,11,size=(6,4));array_3

array([[10,  7,  3,  2],
       [ 6,  5,  2,  7],
       [ 7,  8,  7,  4],
       [ 5,  3,  1,  0],
       [ 7,  4,  1, 10],
       [ 3,  7,  8,  2]])

In [ ]:
split_array_3=np.split(array_3,2,axis=0);split_array_3

[array([[10,  7,  3,  2],
        [ 6,  5,  2,  7],
        [ 7,  8,  7,  4]]),
 array([[ 5,  3,  1,  0],
        [ 7,  4,  1, 10],
        [ 3,  7,  8,  2]])]

In [ ]:
array_4=np.random.randint(0,11,size=(3,6));array_4

array([[ 7,  4,  0,  5,  7,  4],
       [ 4,  1,  0,  8,  6,  7],
       [ 1,  3,  6, 10,  7,  6]])

In [ ]:
split_array_4=np.split(array_4,2,axis=1);split_array_4

[array([[7, 4, 0],
        [4, 1, 0],
        [1, 3, 6]]),
 array([[ 5,  7,  4],
        [ 8,  6,  7],
        [10,  7,  6]])]

### Exercise 8: Mathematical Functions and Aggregations

- Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

- Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

- Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [ ]:
array_8=np.random.randint(1,101,size=15);array_8

array([65, 77, 29, 82,  6, 96, 15, 14, 92, 62,  9, 84, 12, 79, 63])

In [ ]:
print(f"mean:{np.mean(array_8)},median:{np.median(array_8)}, standard_deviation: {np.std(array_8)},variance:{np.var(array_8)}")

mean:52.333333333333336,median:63.0, standard_deviation: 32.77126112244623,variance:1073.9555555555555


In [ ]:
array_81=np.random.randint(1,51,size=(4,4));array_81

array([[ 4, 33, 31, 11],
       [47, 25,  2, 21],
       [10, 33,  7,  8],
       [44, 35, 22, 37]])

### Exercise 9: Reshaping and Transposing Arrays

- Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.

- Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

- Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.

In [ ]:
array_9=np.array(range(1,13)).reshape(3,4);array_9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array_91=np.random.randint(1,11,size=(3,4));array_91

array([[ 1,  2,  5, 10],
       [ 5,  2,  4,  7],
       [ 9,  7,  2,  5]])

In [ ]:
array_91_tr=np.transpose(array_91);array_91_tr

array([[ 1,  5,  9],
       [ 2,  2,  7],
       [ 5,  4,  2],
       [10,  7,  5]])

In [ ]:
array_91_fl=np.random.randint(1,11,size=(2,3)).flatten();array_91_fl

array([8, 4, 6, 3, 4, 6])

### Exercise 10: Broadcasting and Vectorized Operations

- Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

- Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

- Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

In [ ]:
array_10=np.random.randint(1,11,size=(3,4));array_10_mean=np.mean(array_10,axis=0);array_10_mean


array([7.        , 2.66666667, 7.        , 4.33333333])

In [ ]:
array_1 = np.random.randint(1, 6, size=4)
array_2 = np.random.randint(1, 6, size=4)
outer_product = np.outer(array_1, array_2);outer_product

array([[ 4,  5,  3,  4],
       [20, 25, 15, 20],
       [16, 20, 12, 16],
       [ 4,  5,  3,  4]])

In [ ]:
array_10_1=np.random.randint(1,11,size=(4,5))
array_10_1[array_10_1>5]+10;array_10_1

array([[ 4,  5,  3,  3, 10],
       [ 2,  5,  8,  2,  4],
       [ 6,  4,  7,  2,  3],
       [ 3,  1,  1,  1,  8]])

### Exercise 11: Sorting and Searching Arrays

- Create a 1D NumPy array with random integers between 1 and 20 of size 10. Sort the array in ascending order and print the sorted array.

- Create a 2D NumPy array of shape (3, 5) with random integers between 1 and 50. Sort the array by the second column and print the result.

- Create a 1D NumPy array with random integers between 1 and 100 of size 15. Find and print the indices of all elements greater than 50.

In [ ]:
array_11=np.random.randint(1,12,size=10)
np.sort(array_11)

array([ 1,  2,  3,  4,  5,  5,  7,  8,  9, 11])

In [ ]:
array_11_2d=np.random.randint(1,51,size=(3,5));array_11_2d

array([[29, 36,  5, 32,  7],
       [16, 35,  9, 19, 26],
       [48,  4, 34, 18, 28]])

In [ ]:
sorted_array = array_11_2d[array_11_2d[:, 1].argsort()];sorted_array

array([[48,  4, 34, 18, 28],
       [16, 35,  9, 19, 26],
       [29, 36,  5, 32,  7]])

In [ ]:
array_11_1=np.random.randint(1,101,size=15)
array_11_1[array_11_1>50]

array([91, 82, 99, 67, 57, 95, 55])

### Exercise 12: Linear Algebra with NumPy

- Create a 2D NumPy array of shape (2, 2) with random integers between 1 and 10. Compute and print the determinant of the array.

- Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 5. Compute and print the eigenvalues and eigenvectors of the array.

- Create two 2D NumPy arrays of shape (2, 3) and (3, 2) with random integers between 1 and 10. Compute and print the matrix product of the two arrays.

In [ ]:
array_12=np.random.randint(1,11,size=(2,2))
det_array_12=np.linalg.det(array_12);det_array_12

-20.000000000000007

In [ ]:
A=np.random.randint(1,6,size=(3,3))
eigenvalues,eigenvectors=np.linalg.eig(A); eigenvalues,eigenvectors

(array([8.32875262+0.j        , 0.83562369+0.61832599j,
        0.83562369-0.61832599j]),
 array([[ 0.56032725+0.j        ,  0.47927842-0.25058067j,
          0.47927842+0.25058067j],
        [ 0.44638471+0.j        , -0.76363432+0.j        ,
         -0.76363432-0.j        ],
        [ 0.69769196+0.j        ,  0.21495678+0.27956705j,
          0.21495678-0.27956705j]]))

In [ ]:
B=np.random.randint(1,11,size=(2,3))
C=np.random.randint(1,11,size=(3,2))
print(np.dot(B,C))

[[36 86]
 [94 65]]


### Exercise 13: Random Sampling and Distributions

- Create a 1D NumPy array of 10 random samples from a uniform distribution over [0, 1) and print the array.

- Create a 2D NumPy array of shape (3, 3) with random samples from a normal distribution with mean 0 and standard deviation 1. Print the array.

- Create a 1D NumPy array of 20 random integers between 1 and 100. Compute and print the histogram of the array with 5 bins.

In [ ]:
array_13=np.random.uniform(0,1,10);array_13

array([0.30201061, 0.75006904, 0.46556926, 0.75514332, 0.37023976,
       0.26962561, 0.43322893, 0.33811603, 0.89535643, 0.38909513])

In [ ]:
np.random.normal(0,1,size=(3,3))

array([[ 0.43520698, -0.80072527, -0.61626663],
       [-0.02238822, -1.35080576, -0.9664748 ],
       [ 0.49687694, -0.75413247, -1.48000305]])

In [ ]:
random_array=np.random.randint(1,100,20)

In [ ]:
hist, bin_edges = np.histogram(random_array, bins=5)
print(hist)
print(bin_edges)

[4 1 3 6 6]
[ 2. 21. 40. 59. 78. 97.]


### Exercise 14: Advanced Indexing and Selection

- Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 20. Select and print the diagonal elements of the array.

- Create a 1D NumPy array of 10 random integers between 1 and 50. Use advanced indexing to select and print all elements that are prime numbers.

- Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 10. Select and print all elements that are even numbers.

In [ ]:
array_14=np.random.randint(1,21,size=(5,5));array_14

array([[10, 18, 17, 11,  9],
       [10, 14,  7, 16,  5],
       [ 6, 12, 19, 16,  6],
       [ 2, 19, 14, 19,  7],
       [ 2, 10, 10, 15, 13]])

In [ ]:
np.diag(array_14)

array([10, 14, 19, 19, 13])

In [3]:
random_array = np.random.randint(1, 51, size=10)
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_mask = np.array([is_prime(num) for num in random_array])

prime_numbers = random_array[prime_mask]


In [4]:
prime_numbers

array([ 2, 41,  2,  7, 31, 41])

### Exercise 15: Handling Missing Data

- Create a 1D NumPy array of length 10 with random integers between 1 and 10. Introduce `np.nan` at random positions and print the array.

- Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Replace all elements that are less than 5 with `np.nan` and print the array.

- Create a 1D NumPy array of length 15 with random integers between 1 and 20. Identify and print the indices of all `np.nan` values in the array.

In [7]:
array_1d = np.random.randint(1, 11, size=10).astype(float)
print(array_1d)
random_indices = np.random.choice(array_1d.size, size=3, replace=False)
array_1d[random_indices] = np.nan
print(array_1d)

[6. 3. 6. 9. 8. 8. 6. 7. 8. 8.]
[ 6. nan nan  9.  8.  8.  6.  7.  8. nan]


In [8]:
array_2d = np.random.randint(1, 11, size=(3, 4)).astype(float)
array_2d[array_2d < 5] = np.nan
array_2d

array([[ 7.,  8., nan, 10.],
       [ 5.,  7., nan, 10.],
       [ 8.,  6., 10.,  5.]])

In [14]:
array_1d1=np.random.randint(1,21,size=15).astype(float)
random_indices = np.random.choice(array_1d1.size, size=3, replace=False)
array_1d1[random_indices] = np.nan
nan_indices=np.where(np.isnan(array_1d1))
nan_indices

(array([0, 1, 8]),)

### Exercise 16: Performance Optimization with NumPy

- Create a large 1D NumPy array with 1 million random integers between 1 and 100. Compute the mean and standard deviation using NumPy functions and measure the time taken.

- Create two large 2D NumPy arrays of shape (1000, 1000) with random integers between 1 and 10. Perform element-wise addition and measure the time taken.

- Create a 3D NumPy array of shape (100, 100, 100) with random integers between 1 and 10. Compute the sum along each axis and measure the time taken.

In [15]:
array_16=np.random.randint(1,101,size=1000000)
print(np.mean(array_16),np.std(array_16))

50.502514 28.851420340770122


In [ ]:
array_16_2d=np.random.randint(1,11,size=(1000,1000))

In [25]:
import time

array_1d_large = np.random.randint(1, 101, size=1000000)

start_time = time.time()
mean_1d = np.mean(array_1d_large)
std_1d = np.std(array_1d_large)
end_time = time.time()
time_1d = end_time - start_time

print(f"Mean of 1D array: {mean_1d}")
print(f"Standard deviation of 1D array: {std_1d}")
print(f"Time taken for mean and std of 1D array: {time_1d:.6f} seconds")





Mean of 1D array: 50.51452
Standard deviation of 1D array: 28.851840481494417
Time taken for mean and std of 1D array: 0.010160 seconds


In [23]:
array_2d_a = np.random.randint(1, 11, size=(1000, 1000))
array_2d_b = np.random.randint(1, 11, size=(1000, 1000))

start_time = time.time()
array_2d_sum = array_2d_a + array_2d_b
end_time = time.time()
time_2d_addition = end_time - start_time

print(f"\nTime taken for element-wise addition of 2D arrays: {time_2d_addition:.6f} seconds")


Time taken for element-wise addition of 2D arrays: 0.012854 seconds


In [24]:
array_3d = np.random.randint(1, 11, size=(100, 100, 100))

start_time = time.time()
sum_axis_0 = np.sum(array_3d, axis=0)
sum_axis_1 = np.sum(array_3d, axis=1)
sum_axis_2 = np.sum(array_3d, axis=2)
end_time = time.time()
time_3d_sum = end_time - start_time

print(f"\nTime taken to compute sum along all axes for 3D array: {time_3d_sum:.6f} seconds")


Time taken to compute sum along all axes for 3D array: 0.003175 seconds


### Exercise 17: Cumulative and Aggregate Functions

- Create a 1D NumPy array with the numbers from 1 to 10. Compute and print the cumulative sum and cumulative product of the array.

- Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 20. Compute and print the cumulative sum along the rows and the columns.

- Create a 1D NumPy array with 10 random integers between 1 and 50. Compute and print the minimum, maximum, and sum of the array.

In [26]:

array_1d = np.arange(1, 11)

cumulative_sum = np.cumsum(array_1d)
cumulative_product = np.cumprod(array_1d)

print("1D array:", array_1d)
print("Cumulative sum:", cumulative_sum)
print("Cumulative product:", cumulative_product)


1D array: [ 1  2  3  4  5  6  7  8  9 10]
Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]
Cumulative product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [27]:
array_2d = np.random.randint(1, 21, size=(4, 4))

cumsum_rows = np.cumsum(array_2d, axis=1)
cumsum_columns = np.cumsum(array_2d, axis=0)

print("\n2D array:")
print(array_2d)
print("Cumulative sum along rows:")
print(cumsum_rows)
print("Cumulative sum along columns:")
print(cumsum_columns)


2D array:
[[11 16  5  5]
 [12  5 18  1]
 [12  5 17  4]
 [ 1  4 17  6]]
Cumulative sum along rows:
[[11 27 32 37]
 [12 17 35 36]
 [12 17 34 38]
 [ 1  5 22 28]]
Cumulative sum along columns:
[[11 16  5  5]
 [23 21 23  6]
 [35 26 40 10]
 [36 30 57 16]]


In [28]:
array_1d_random = np.random.randint(1, 51, size=10)


min_value = np.min(array_1d_random)
max_value = np.max(array_1d_random)
sum_value = np.sum(array_1d_random)

print("\n1D random array:", array_1d_random)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Sum of the array:", sum_value)



1D random array: [35 15 11 43 24  5 26 42 16 26]
Minimum value: 5
Maximum value: 43
Sum of the array: 243


### Exercise 18: Working with Dates and Times

- Create an array of 10 dates starting from today with a daily frequency and print the array.

- Create an array of 5 dates starting from January 1, 2022 with a monthly frequency and print the array.

- Create a 1D array with 10 random timestamps in the year 2023. Convert the timestamps to NumPy datetime64 objects and print the result.

In [29]:
dates_daily = np.arange(np.datetime64('today'), np.datetime64('today') + 10, dtype='datetime64[D]')
print("Array of 10 daily dates starting from today:")
print(dates_daily)



Array of 10 daily dates starting from today:
['2024-09-27' '2024-09-28' '2024-09-29' '2024-09-30' '2024-10-01'
 '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-05' '2024-10-06']


In [30]:
dates_monthly = np.arange(np.datetime64('2022-01-01'), np.datetime64('2022-01-01') + 5, dtype='datetime64[M]')
print("\nArray of 5 monthly dates starting from January 1, 2022:")
print(dates_monthly)




Array of 5 monthly dates starting from January 1, 2022:
[]


In [31]:
random_days_2023 = np.random.randint(0, 365, size=10)
timestamps_2023 = np.datetime64('2023-01-01') + random_days_2023
print("\nArray of 10 random timestamps in 2023:")
print(timestamps_2023)


Array of 10 random timestamps in 2023:
['2023-06-06' '2023-06-14' '2023-10-15' '2023-12-10' '2023-12-21'
 '2023-05-06' '2023-03-14' '2023-12-05' '2023-11-24' '2023-01-17']


### Exercise 19: Creating Arrays with Custom Data Types

- Create a 1D NumPy array of length 5 with custom data type to store integers and their corresponding binary representation as strings. Print the array.

- Create a 2D NumPy array of shape (3, 3) with a custom data type to store complex numbers. Initialize the array with some complex numbers and print the array.

- Create a structured array to store information about books with fields: title (string), author (string), and pages (integer). Add information for three books and print the structured array.

In [39]:

dtype_1d = [('number', np.int32), ('binary', 'U10')]
data_1d = [(i, bin(i)[2:]) for i in range(1, 6)]
array_1d = np.array(data_1d, dtype=dtype_1d)
print("1D array with integers and their binary representation:")
print(array_1d)



1D array with integers and their binary representation:
[(1, '1') (2, '10') (3, '11') (4, '100') (5, '101')]


In [40]:
dtype_2d = np.dtype([('complex_num', np.complex128)])
data_2d = np.array([[(1+2j), (3+4j), (5+6j)],
                    [(7+8j), (9+10j), (11+12j)],
                    [(13+14j), (15+16j), (17+18j)]], dtype=dtype_2d)
print("\n2D array with complex numbers:")
print(data_2d)




2D array with complex numbers:
[[( 1. +2.j,) ( 3. +4.j,) ( 5. +6.j,)]
 [( 7. +8.j,) ( 9.+10.j,) (11.+12.j,)]
 [(13.+14.j,) (15.+16.j,) (17.+18.j,)]]


In [41]:
dtype_books = [('title', 'U50'), ('author', 'U50'), ('pages', np.int32)]
books_data = [
    ('The Great Gatsby', 'F. Scott Fitzgerald', 218),
    ('1984', 'George Orwell', 328),
    ('To Kill a Mockingbird', 'Harper Lee', 281)
]
structured_array_books = np.array(books_data, dtype=dtype_books)
print("\nStructured array with book information:")
print(structured_array_books)



Structured array with book information:
[('The Great Gatsby', 'F. Scott Fitzgerald', 218)
 ('1984', 'George Orwell', 328)
 ('To Kill a Mockingbird', 'Harper Lee', 281)]


### Exercise 20: Creating Arrays with Custom Data Types

- Create a 1D NumPy array of length 5 with custom data type to store integers and their corresponding binary representation as strings. Print the array.

- Create a 2D NumPy array of shape (3, 3) with a custom data type to store complex numbers. Initialize the array with some complex numbers and print the array.

- Create a structured array to store information about books with fields: title (string), author (string), and pages (integer). Add information for three books and print the structured array.

In [42]:
dtype_custom_1d = [('number', np.int32), ('binary', 'U10')]
data_1d = [(i, bin(i)[2:]) for i in range(1, 6)]
array_1d_custom = np.array(data_1d, dtype=dtype_custom_1d)
print("1D array with integers and their binary representation:")
print(array_1d_custom)






1D array with integers and their binary representation:
[(1, '1') (2, '10') (3, '11') (4, '100') (5, '101')]


In [43]:
dtype_custom_2d = np.dtype([('complex_num', np.complex128)])
data_2d = np.array([[(1+2j), (3+4j), (5+6j)],
                    [(7+8j), (9+10j), (11+12j)],
                    [(13+14j), (15+16j), (17+18j)]], dtype=dtype_custom_2d)

print("\n2D array with complex numbers:")
print(data_2d)


2D array with complex numbers:
[[( 1. +2.j,) ( 3. +4.j,) ( 5. +6.j,)]
 [( 7. +8.j,) ( 9.+10.j,) (11.+12.j,)]
 [(13.+14.j,) (15.+16.j,) (17.+18.j,)]]


In [44]:
dtype_books = [('title', 'U50'), ('author', 'U50'), ('pages', np.int32)]
books_data = [('The Great Gatsby', 'F. Scott Fitzgerald', 218),
              ('1984', 'George Orwell', 328),
              ('To Kill a Mockingbird', 'Harper Lee', 281)]
structured_array_books = np.array(books_data, dtype=dtype_books)

print("\nStructured array with book information:")
print(structured_array_books)


Structured array with book information:
[('The Great Gatsby', 'F. Scott Fitzgerald', 218)
 ('1984', 'George Orwell', 328)
 ('To Kill a Mockingbird', 'Harper Lee', 281)]
